### ISSUE TITLE
Port to node 0.12

### ISSUE THREAD

**Issue by antoniobusrod** [adaltas/node-krb5#1]
Hello, I think this module is only compatible with node 0.10 cause v8. Are you thinking to port node-krb5 to version 0.12? Thanks!

**Comment by Pierrotws** [comment]
Hi,

This module needs a deep rewrite. The C/C++ code works, but it is not well
written. I will work on it soon and port it for 0.12.
Have you used it before ?

**Comment by antoniobusrod** [comment]
Hello Pierre,

I think this module is out of my scope, because I need to validate a SPNEGO
token (from clients) with a KDC. Do you know if it has been implemented in
Node.js?

**Comment by Pierrotws** [comment]
Yes, this modules is (for now) out of your scope.
I don't think there is yet a module to validate a spnego ticket in nodejs. It is not very different than this module, we only need to call the "opposite" functions in the GSSAPI-Kerberos C library.
I will implement it in the future, but I don't know when...

**Comment by antoniobusrod** [comment]
No worries, I am going to implement a module for this feature.

--
Antonio Bustos R.
http://antonio.busrod.net

**Comment by rainfore** [comment]
I have the same problem. Hope it can be used with node 0.12 soon. Thanks!

**Comment by Pierrotws** [comment]
I am porting code to NAN, so just wait few days

**Comment by Pierrotws** [comment]
Port is done, please feel free to report any troubles with this rewrite
