### ISSUE TITLE
SPNEGO: be more generic for service name

### ISSUE THREAD

**Issue by RReivax** [adaltas/node-krb5#13]
**Current behavior**

```coffeescript
krb5.spnego
  service_fqdn: 'fully.qualified.domain'
, (err, token) ->
```
`service_fqdn` is replaced by HTTP@fully.qualified.domain

OR
```coffeescript
krb5.spnego
  service_fqdn: 'HTTP@fully.qualified.domain'
, (err, token) ->
```
**Issue**
Current implementation assumes that the service principal for SPNEGO is always `HTTP/fqdn`.

**New implementation**
*Option 1:*
[gss_import_name](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.euvfb00/impnm.htm) requires `service@host` when `input_name_type` is `GSS_C_NT_HOSTBASED_SERVICE` (current value).
Make HTTP the default service and allow other services name.
We could have something like:
```coffeescript
krb5.spnego
  hostbased_service: 'hbase@fully.qualified.domain'
, (err, token) ->
```

*Option 2:*
Use `GSS_C_NT_USER_NAME` for [gss_import_name](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.euvfb00/impnm.htm). 
We then need to provide the Kerberos principal associated with the service.
We could have something like:
```coffeescript
krb5.spnego
  service_principal: 'http/fully.qualified.domain'
, (err, token) ->
```
OR
```coffeescript
krb5.spnego
  service_principal: 'http/fully.qualified.domain@REALM'
, (err, token) ->
```

*Option 3:*
Combine both options depending on rather `service_principal` or `hostbased_service` is given.

**Comment by wdavidw** [comment]
Isn't the `HTTP/fqdn` convention part of the SPNEGO specification ?

**Comment by RReivax** [comment]
Could be, I will look further into it, but I ran into this problem when trying to generate a SPNEGO token for HBase Thrift server, requiring a token generated from `hbase/fqdn` .

**Comment by RReivax** [comment]
`HTTP/fqdn` looks like a commonly used convention (eg. [Hadoop](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/SecureMode.html), or [Microsoft Windows](https://tools.ietf.org/html/rfc4559#section-4.1) ) but I don't see it as part of [SPNEGO specification](https://tools.ietf.org/html/rfc4559).

As for the HBase thrift case:
`hbase.thrift.kerberos.principal` generally has for value `hbase/_HOST@REALM` which seems logical, same for HBase REST. 
The Kerberos principal used to access the REST service via HTTP/SPNEGO is indeed  `HTTP/_HOST@REALM`, namely the value of  `hbase.security.authentication.spnego.kerberos.principal`
However, the principal for accessing the Thrift server via HTTP/SPNEGO  remains `hbase/_HOST@REALM` and not `HTTP/_HOST@REALM`. 
That might be because the Thrift server is not only accessible via HTTP, but still, not sure if that is correct behaviour.

**Comment by wdavidw** [comment]
It makes sense in the case of Thrift

**Comment by Pierrotws** [comment]
HTTP/fqdn is not in the spec of SPNEGO, since SPNEGO is not Kerberos specific.
SPNEGO does not allow service discovery, so Kerberos clients cannot assume server principal.
HTTP/fqdn is not a convention, it's a deterministic principal name that can be computed by the client.
Actually you can allow node-krb5 to overload server principal, but no other client would work, so I don't think it is very useful.
