### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by heyitsvajid** [adaltas/node-krb5#16]
vkagdi$ node --version
v8.16.1
vkagdi$ npm --version
6.4.1

#### Getting below error when trying to install this module on Mac.  We are using `hbase` module and it has kerberos authentication. So we need this module to enable authentication to HBase from NodeJS.

```
LM-SJN-40004088:server vkagdi$ npm install krb5 --save

> krb5@0.5.1 install /Users/.../server/node_modules/krb5
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/krb5/src/module.o
In file included from ../src/module.cc:1:
In file included from ../src/krb5_bind.h:1:
/Users/.../server/node_modules/node-addon-api/napi.h:31:6: error: Exception support not detected. Define either NAPI_CPP_EXCEPTIONS or
      NAPI_DISABLE_CPP_EXCEPTIONS.
    #error Exception support not detected. \
     ^
1 error generated.
make: *** [Release/obj.target/krb5/src/module.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@8/8.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node@8/8.16.1/bin/node" "/usr/local/Cellar/node@8/8.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/...server/node_modules/krb5
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN customerjourneynodeweb@2.3.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! krb5@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the krb5@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vkagdi/.npm/_logs/2019-08-26T17_40_07_693Z-debug.log
```

**Comment by andrewsheffield** [comment]
+1

**Comment by wdavidw** [comment]
I tried, with no success. @RReivax remind me to look toguether on the train on sunday evening

**Comment by wdavidw** [comment]
OSX is now working.

**Comment by liberona91** [comment]
Same problem here. I have python in the project path, and it says the same problem described by @heyitsvajid

**Comment by wolf-allywilson** [comment]
/usr/bin/python is v2.7.8 on my system, and it still appears to choose python3 for me.

`PATH="/usr/bin:$PATH" npm install krb5`

> npm ERR! code 1
> npm ERR! path /Users/myUser/repos/misc/myProj/node_modules/krb5
> npm ERR! command failed
> npm ERR! command sh -c node-gyp rebuild
> npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
> npm ERR!   LIBTOOL-STATIC Release/nothing.a
> npm ERR!   CXX(target) Release/obj.target/krb5/src/module.o
> npm ERR!   CXX(target) Release/obj.target/krb5/src/krb5_bind.o
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@8.3.0
> npm ERR! gyp info using node@14.17.0 | darwin | x64
> npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
> npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',

OS: macOS Monterey
node: 14.17.0
npm: 8.1.1

**Comment by gboutry** [comment]
With latest version, it's python 3 that is required to build the shared library.
Node-gyp dropped the python 2 support

Can you give the full log ?

**Comment by wolf-allywilson** [comment]
Sure, please see attached
[output.log](https://github.com/adaltas/node-krb5/files/8080593/output.log)
[debug.log](https://github.com/adaltas/node-krb5/files/8080594/debug.log)
.

**Comment by gboutry** [comment]
This is not a python related issue, but a compilation one.
The error is that we give a const pointer to a function waiting for a non-const pointer (Meaning we're giving something that shouldn't be changed to something that can change it, which is a big no-no).

The two functions are:
- `krb5_get_init_creds_password`
- `krb5_get_init_creds_keytab`

I'll take `krb5_get_init_creds_password` as an example.
Error:
```log
npm ERR! ../src/krb5_bind.cc:635:13: error: no matching function for call to 'krb5_get_init_creds_password'
npm ERR!       err = krb5_get_init_creds_password(krb_context, 
npm ERR!             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:2302:1: note: candidate function not viable: 4th argument ('const std::basic_string<char>::value_type *' (aka 'const char *')) would lose const qualifier
npm ERR! krb5_get_init_creds_password
npm ERR! ^
```

Function signature from krb5.h:
```c
krb5_get_init_creds_password(krb5_context context, krb5_creds *creds,
                             krb5_principal client, const char *password,
                             krb5_prompter_fct prompter, void *data,
                             krb5_deltat start_time,
                             const char *in_tkt_service,
                             krb5_get_init_creds_opt *k5_gic_options);
```

What we do is:
```cpp
  err = krb5_get_init_creds_password(krb_context, 
                                     &creds,
                                     krb_princ,
                                     krb_password.c_str(),
                                     nullptr,
                                     nullptr,
                                     0,
                                     NULL,
                                     nullptr);
```

As you can see, the 4th argument is `krb_password.c_str()`, which, called on a string returns a `const char*`, which matches the function definition.

Therefore, there must be a problem with either your libc, or your libkrb5 includes.

How did you install libkrb5 ? and what is its version ?

**Comment by wolf-allywilson** [comment]
Glancing at the logs, looks it's coming down from an official Apple SDK?

> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:

Not sure how to check that version.

However, I do have krb5 installed via Brew (v1.19.2):

> /usr/local/Cellar/krb5/1.19.2

**Comment by wolf-allywilson** [comment]
Same thing I'm afraid, seems to ignore and use the SDK version?

[output.log](https://github.com/adaltas/node-krb5/files/8081056/output.log)

**Comment by wolf-allywilson** [comment]
This worked:

```
export LIBRARY_PATH="/usr/local/Cellar/krb5/1.19.2/lib"
export CPLUS_INCLUDE_PATH="/usr/local/Cellar/krb5/1.19.2/include"                          
npm install krb5
```

> 
> added 4 packages, and removed 7 packages in 7s
> 
> 82 packages are looking for funding
>   run `npm fund` for details

Thank you very much!
