### ISSUE TITLE
Missing krb5.h header file when compiling on Windows

### ISSUE THREAD

**Issue by royprigat** [adaltas/node-krb5#20]
After following the instructions provided to compile the library in Windows, I keep getting a build error indicating the the krb5.h file cannot be found:

```
Build FAILED.

"C:\Users\rprigat\Desktop\node-krb5-master\build\binding.sln" (default target) (1) ->
"C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.vcxproj.metaproj" (default target) (2) ->
"C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.vcxproj" (default target) (4) ->
(ClCompile target) ->
  c:\users\rprigat\desktop\node-krb5-master\src\krb5_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h':
No such file or directory (compiling source file ..\src\krb5_bind.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\
krb5.vcxproj]
  c:\users\rprigat\desktop\node-krb5-master\src\krb5_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h':
No such file or directory (compiling source file ..\src\module.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\krb
5.vcxproj]
  c:\users\rprigat\desktop\node-krb5-master\src\gss_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h': N
o such file or directory (compiling source file ..\src\gss_bind.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\kr
b5.vcxproj]

    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:02.05
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\rprigat\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rprigat\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--verbose"
gyp ERR! cwd C:\Users\rprigat\Desktop\node-krb5-master
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
```

I am using node 10, python 2.7 and installed the VS 2017 Community with the relevant C++ workload.

Any idea why this might happen?

**Comment by rs-saunders** [comment]
I also have this issue. Does anyone have the file that we could manually add it in? Has this project been abandoned?

**Comment by karthikeya93** [comment]
I have the same Issue. When I install MIT Kerberos in windows, There are no header files in any folders. Only windows .dll and .exe files.

**Comment by Guillaume-Boutry** [comment]
If you've used the graphical installer, the SDK is an option, you have to manually select it to have the headers installed.

To have all options installed, run from powershell:
`.\kfw-4.1-amd64.msi /qn/norestart ADDLOCAL=ALL`

Or if you use chocolatey:
`choco install mitkerberos --ia="ADDLOCAL=add"` (error 3010 is normal, it means a reboot is required)

Moreover, be sure to install MIT Kerberos to the default location since the node-gyp will look in this path.
(As defined in `binding.gyp` )

**Comment by wdavidw** [comment]
@Guillaume-Boutry Thank you for helping out. If you estimate the addition relavant, could you share those instructions in the readme.

**Comment by Guillaume-Boutry** [comment]
@wdavidw 
I will.

I also have a vagrantfile with an Ansible provisionning setup that installs a Windows 10 box with all the compilation tool needed. It could serve at least as an example or to devs to be able to test the build on window. Do you want me to add it to the repository ?

I would add it in 
/vagrant
--/Vagrantfile
--/provisionning.yaml

**Comment by wdavidw** [comment]
Yes, please!

**Comment by Guillaume-Boutry** [comment]
Hi,

Answers were provided.

Don't hesitate to look in #28  (vagrant file + ansible playbook setting up a Windows VM) or in #33 (Github job building Windows) to check how we install MIT Kerberos with the SDK.

Closing this issue, don't hesitate to open another one if you have any issue.
