### ISSUE TITLE
*** stack smashing detect *** for spnego tokens bigger than 2048

### ISSUE THREAD

**Issue by ClaudioCavalcanteVas** [adaltas/node-krb5#21]
When I tried to get a spnego token from my company's kerberos, I received the `*** stack smashing detect ***` error. 

After run some validations into `src/gss_bind.cc` file, I could realize that the token sent by the server is bigger than the 2048 set into the `token_buffer` variable, thus the N-API code cannot return this value to Node and it gave me an overflow error.

To solve the problem for now, I raised the value to 4056 and published into our package manager. I really don't know if this is the best solution, but if true, I can open a pull request here with the change.

Anyway, I will wait the fix suggestion or the module's update to come back to use this.

Thank you!

**Comment by wdavidw** [comment]
Thank you for reporting, I think you could prepare a pull request and @RReivax will review it.

**Comment by Guillaume-Boutry** [comment]
Since PR #32, the maximum size has been set to 48 000 bytes, (it was 2 048 bytes before).
This should give you enough space to work with Windows AD (48KB is the recommended max value in Microsoft Documentation)

Closing this issue, don't hesitate to open a new issue if you have any trouble.
