### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by simon-p-r** [adaltas/node-krb5#3]
Hi

I'm trying to find out how to retrieve the Kerberos token using node-krb5 in case of successful authentication. My use case is as following

```shell
1. Client app provides username/password to node server app
2. Node authenticates the user with the provided credentials against Kerberos
3. Kerberos provides a spnego token that node app will send back to client
4. Client sends the token for every request to node to enable authentication 
````
Thanks
Simon

**Comment by Pierrotws** [comment]
Hi,

First of all this plugin is not yet compatible with node 0.12. I'm not sure
to truely understand your need.
In node js, as shown in kinit_kdestroy.js sample

Instantiate krb5 with principal and password.

Then please do a k.kinit once to proceed kerberos authentication.

Kerberos is SSO, so each time you need a unique ticket, use spnego method.

This projet is a kerberos client to contact kerberized web service. You
cannot use this module to securize your own application.

Don't be shy if you need more information !

**Comment by simon-p-r** [comment]
Thank you this has answered my question, are there any plans to implement kerberos on server to enable securing our own application.

**Comment by Pierrotws** [comment]
Yes there is, but we don't know when.

Port to 0.12 is more important, and require a complete rewrite, so I can't
give you a delivery date.

Pierre Sauvage

2015-07-14 20:08 GMT+02:00 Simon R <notifications@github.com>:

**Comment by simon-p-r** [comment]
Ok thanks Pierre

If I can help I will prepare a pull request, I have not much experience with c++ but writing the bindings for the port to 0.12 and exposing more of the api from the kerberos library could be possible.

Best regards
Simon

**Comment by Pierrotws** [comment]
With pleasure !

Pierre Sauvage

2015-07-15 11:56 GMT+02:00 Simon R <notifications@github.com>:
