### ISSUE TITLE
Read krb5.conf from environment variable if supplied

### ISSUE THREAD

**Issue by willm** [adaltas/node-krb5#6]
the native `kinit` command allows you to override the default location for krb5.conf if you set the `KRB5_CONFIG` environment variable https://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html maybe this could be a nice feature for this package too?

**Comment by wdavidw** [comment]
agreed

**Comment by yuu2lee4** [comment]
nice

**Comment by RReivax** [comment]
This feature is present.
